networks:
  flexds-compose-yaml:
    driver: bridge

services:
  flexds:
    build:
      context: ..
      dockerfile: container/Containerfile
    container_name: flexds
    command:
      - "-yaml"
      - "-yaml-file"
      - "/etc/flexds/static-services.yaml"
      - "-ads-port"
      - "18000"
      - "-admin-port"
      - "19005"
      - "-debug"
    volumes:
      - ./configs/static-services.yaml:/etc/flexds/static-services.yaml:ro
    networks:
      - flexds-compose-yaml
    environment:
      - GOMAXPROCS=2
    ports:
      - "18000:18000" # ADS gRPC
      - "19005:19005" # admin HTTP

  envoy-proxy-1:
    image: envoyproxy/envoy:v1.36.4
    container_name: envoy-proxy-1
    depends_on:
      - flexds
    volumes:
      - ./configs/envoy-bootstrap.yaml:/etc/envoy/bootstrap.yaml:ro
    ports:
      - "18080:18080"
      - "19000:19000"
    command:
      - "-c"
      - "/etc/envoy/bootstrap.yaml"
      - "--service-node"
      - "envoy-proxy-1"
      - "--log-level"
      - "info"
    networks:
      - flexds-compose-yaml

  rest-service-1:
    build:
      context: ./rest-service
      dockerfile: Containerfile
    container_name: rest-service-1
    ports:
      - "8080:8080"
    networks:
      - flexds-compose-yaml
    environment:
      - FLASK_ENV=production
      - CONSUL_HOST=consul-agent
      - CONSUL_PORT=8500
      - SERVICE_NAME=hello-service
      - SERVICE_ID=hello-service-1:8080
      - SERVICE_PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - consul-agent

  grpc-service-1:
    build:
      context: ./grpc-service
      dockerfile: Containerfile
    container_name: grpc-service-1
    ports:
      - "9090:9090"
    networks:
      - flexds-compose-yaml
    environment:
      - CONSUL_HOST=consul-agent
      - CONSUL_PORT=8500
      - SERVICE_NAME=grpc-service
      - SERVICE_ID=grpc-service-1:9090
    depends_on:
      - consul-agent
